### ISSUE TITLE
can't open a collection

### ISSUE THREAD

**Issue by mindfocus** [Its-treason/bruno#14]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I choose a collection to open, but bruno say "Collection is already opened", and there is nothing opened

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/db35e5e0-828d-412a-8428-1e856df2ca5c)

**Comment by mindfocus** [comment]
![image](https://github.com/user-attachments/assets/70ce60c9-6ba7-48ff-bd89-3f03bdb8ccd0)

**Comment by Its-treason** [comment]
Hey @mindfocus, thanks for reporting! I did not notice, that the port can be null while creating the schema. I fixed the schema and this should work now. Let me know, if you still have problems.
