### ISSUE TITLE
Error with tests defined as external scritpt

### ISSUE THREAD

**Issue by tlaloc911** [Its-treason/bruno#6]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am testing with nigthly lazer a collection that works with usebruno's version

If I try to use tests defined in external script it fails, if I put the content directly it works

<img width="379" alt="image" src="https://github.com/Its-treason/bruno/assets/29415755/dc568e7c-0e47-46da-bc0f-184bc13897a6">

at testing any request:

~~~
Error invoking remote method 'send-http-request': Error: Failed to require "../scripts/tests-stub.js"!

If you tried to require a internal node module / external package, make sure its whitelisted in the "bruno.json" under "scriptConfig".
If you wanted to require an external script make sure the path is correct or added to "additionalContextRoots" in your "bruno.json".

We searched the following paths for your script:
- "C:\Users\xxx\Documents\dev\collections\scripts\tests-stub.js": ReferenceError: test is not defined
,- "C:\Users\xxx\Documents\dev\collections\scripts\tests-stub.js": ReferenceError: test is not defined


~~~

Layout: there is a "scripts" folder shared by several collections

~~~
🗁collections
    🗁scripts
           tests-stub.js
    🗁 collection1
           bruno.js
    🗁 collection2
~~~

### .bru file to reproduce the bug

bruno.js
~~~
{
  "version": "1",
  "name": "collection1",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git",
    "logs",
    "expected"

  ],
  "scripts": {
    "additionalContextRoots": [
      "../scripts"
    ],
    "moduleWhitelist": [
      "fs",
      "path",
      "moment",
      "xmldom",
      "url",
      "xml-formatter",
      "handlebars"
    ],
    "filesystemAccess": {
      "allow": true
    }
  }
}

~~~

tests-stub.js
~~~

test("HTTP OK", function() {
    expect(res.status).to.equal(200);
 });
~~~

### Screenshots/Live demo link

![image](https://github.com/Its-treason/bruno/assets/29415755/046f7b38-97b9-4040-ab09-4868418aa5cb)

**Comment by tlaloc911** [comment]
Hi @Its-treason, no worries at all! I appreciate you taking the time to look into the issue.

The first time I run a request it works, but from the second time on, it doesn't. Test tab says "No tests found" but the debug Tab still shows information about the script. You have to restart the app to have another shot.

**First time**
![image](https://github.com/Its-treason/bruno/assets/29415755/03703695-935b-482e-bf85-67b6908ea2cd)

![image](https://github.com/Its-treason/bruno/assets/29415755/078a61ad-6a9a-45ca-aeb7-25823d35baf7)


**The second time on** 

![image](https://github.com/Its-treason/bruno/assets/29415755/998e746d-8493-4feb-b2cb-679f9e6dd87a)


![image](https://github.com/Its-treason/bruno/assets/29415755/770313bf-a4ba-49f4-9e6c-ff59ecfcfcf8)

**Comment by Its-treason** [comment]
Hey @tlaloc911, thanks for the feadback. I identified the problem: Node was caching your script inside the require cache.

I published the fix in the latest nightly release.

**Comment by tlaloc911** [comment]
Thanks @Its-treason!, it works now.
